name: Build_Container

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/zephyr-build:v0.26.4
    strategy:
      matrix:
        sample: [blinky]
        target: [nrf52833dk_nrf52833]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: nfed

      - name: Set variables
        working-directory: nfed
        id: vars
        run: |
             echo "::set-output name=branch::${GITHUB_REF#refs/*/}"
             echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build ${{ matrix.sample }} for ${{ matrix.target }}
        working-directory: nfed
        run: |
          west build -b ${{ matrix.target }} -s samples/${{ matrix.sample }} -p
          mkdir -p .out
          cp build/zephyr/app_update.bin .out/${{ matrix.sample }}_${{ matrix.target }}_app_update.bin
          cp build/zephyr/merged.hex .out/${{ matrix.sample }}_${{ matrix.target }}_merged.hex

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: nfed_${{ steps.vars.outputs.branch }}_${{ steps.vars.outputs.sha_short }}
          path: nfed/.out/
